export const homeObjOne = {
  id: "reviews",
  lightBg: false,
  lightText: true,
  lighTextDesc: true,
  topLine: "Sarah H",
  headline: "Amazing Groomer, Highly Recommend",
  description: "Type of dog or services given",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: "review-3.png",
  alt: "review 1",
  primary: true,
  darkText: false,
};
