import Head from "next/head";
import Form from "../components/Form/Form";
import Hero from "../components/Hero/Hero";
import Pricing from "../components/Pricing/Pricing";
import { homeObjOne } from "../components/Reviews/Data";
import Review from "../components/Reviews/Review";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dog Grooming in Tonbridge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Pricing />
      <Review {...homeObjOne} />
      <Form />
    </>
  );
}
